config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'static#home'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  get '/profile/:username', to: 'users#show', as: 'user'
  get '/profile/:username/bio', to: 'users#bio', as: 'user_bio'
  patch '/profile/:username/bio', to: 'users#edit_bio'

  get '/profile/:username/bikes', to: 'bikes#index', as: 'user_bikes'
  get '/profile/:username/bikes/new', to: 'bikes#new', as: 'new_bike'
  post '/profile/:username/bikes/new', to: 'bikes#create'
  get '/profile/:username/bikes/:id', to: 'bikes#show', as: 'bike'
  get '/profile/:username/bikes/:id/edit', to: 'bikes#edit', as: 'edit_bike'
  patch '/profile/:username/bikes/:id/edit', to: 'bikes#update'
  delete '/profile/:username/bikes/:id', to: 'bikes#delete', as: 'delete_bike'

  get '/profile/:username/rides', to: 'rides#user_index', as: 'user_rides'
  get '/rides', to: 'rides#index'
  get '/rides/new', to: 'rides#new', as: 'new_ride'
  post '/rides', to: 'rides#create'
  get '/rides/:id', to: 'rides#show', as: 'ride'
  get '/rides/:id/edit', to: 'rides#edit', as: 'edit_ride'
  patch '/rides/:id/complete', to: 'rides#complete', as: 'complete_ride'
  patch '/rides/:id/join', to: 'rides#join', as: 'join_ride'
  patch '/rides/:id/leave', to: 'rides#leave', as: 'leave_ride'
  patch '/rides/:id', to: 'rides#update'
  delete '/rides/:id', to: 'rides#delete', as: 'delete_ride'
  get '/next-big-one', to: 'rides#next_big_one', as: 'next_big_one'
  get '/rides/:id/edit-stats', to: 'participants#edit', as: 'edit_ride_stats'
  patch '/rides/:id/edit-stats', to: 'participants#update'

  get '/leaderboard', to: 'leaderboard#index'

  get '/auth/github/callback' => 'sessions#omniauth'
end

app/models/user.rb
class User < ActiveRecord::Base

    has_secure_password
    has_many :bikes
    has_many :rides_created, class_name: "Ride"
    has_many :components, :through =>  :bikes
    has_many :participants
    has_many :rides, :through => :participants

    validates_presence_of :username, :name, :email, :password
    validates :username, format: { with: /\A[a-zA-Z0-9]+\Z/ }
    validates :username, uniqueness: true
    validates :email, uniqueness: true

    def self.leaderboard
        user_miles = {}
        self.all.each do |user|
            user_miles[user] = user.mileage
        end
        user_miles.sort_by {|k, v| -v}
    end

    def mileage
        miles = 0
        rides.each do |ride|
            if ride.completed
                miles += ride.distance.to_i
            end
        end
        miles
    end

    def current_ride_stats(ride)
        participants.find_by(ride_id: ride.id)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to user_path(@user.username)
        else
            render :new
        end 
    end

    def bio
        @user = User.find_by(username: params[:username])
        if logged_in? && @user == current_user
            render :bio
        else
            redirect_to user_path(@user.username)
        end
    end

    def edit_bio
        if user_params[:password].blank?
            user_params.delete(:password)
        end
        @user = User.find_by(username: params[:username])
        @user.update(user_params)
        redirect_to user_path(@user.username)
    end

    def show
        @user = User.find_by(username: params[:username])
    end

    private

    def user_params
        params.require(:user).permit(:username, :password, :email, :name, :bio)
    end

end

app/views/users/bio.html.erb
<h3>Add Something About Yourself!</h3>
<br>
<%= form_for @user, url: user_bio_path do |f| %>

    <%= f.text_area :bio, value: @user.bio %>
    <br>
    <%= f.submit "Update Bio" %>
  
<% end %>

app/views/users/new.html.erb
<h3>Join the Peleton!</h3>

<% if @user.errors.any? %>
  <div style="color:red;">
    <h4>There were some errors:</h4>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @user, url: signup_path do |f| %>
  
  <%= f.label name="username", value="Username:" %>
  <%= f.text_field :username %>
  <br>
  <br>
  <%= f.label name="email", value="E-Mail:" %>
  <%= f.text_field :email %>
  <br>
  <br>
  <%= f.label name="password", value="Password:" %>
  <%= f.password_field :password %>
  <br>
  <br>  <%= f.label name="name", value="Name:" %>
  <%= f.text_field :name %>
  <br>
  <br>
  <%= f.submit "Sign Up" %>

<% end %>

app/views/users/show.html.erb
<h1>@<%= @user.username %></h1>
<h4><%= @user.name %></h4>
<% if @user == current_user %>
    <br>
    <%= form_tag user_bikes_path(@user.username), method: :get do %>
        <%= submit_tag "My Bikes" %> 
    <% end %>
    <br>
    <%= form_tag user_rides_path(@user.username), method: :get do %>
        <%= submit_tag "My Rides" %> 
    <% end %>
    <br>
<% else %>
    <br>
    <%= form_tag user_bikes_path(@user.username), method: :get do %>
        <%= submit_tag "#{@user.name}'s Bikes" %> 
    <% end %>
    <br>
    <%= form_tag user_rides_path(@user.username), method: :get do %>
        <%= submit_tag "#{@user.name}'s Rides" %> 
    <% end %>
    <br>
<% end %>
<strong>Odometer:</strong> <%= @user.mileage %> Miles
<br>
<br>
<strong>About:</strong>
<p style="max-width: 600px;"><%= @user.bio %></p> 
<br>
<% if @user == current_user %>
    <%= form_tag user_bio_path(@user.username), method: :get do %>
        <%= submit_tag "Edit Bio" %> 
    <% end %>
<% end %>