config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'static#home'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  get '/profile/:username', to: 'users#show', as: 'user'
  get '/profile/:username/bio', to: 'users#bio', as: 'user_bio'
  patch '/profile/:username/bio', to: 'users#edit_bio'

  get '/profile/:username/bikes', to: 'bikes#index', as: 'user_bikes'
  get '/profile/:username/bikes/new', to: 'bikes#new', as: 'new_bike'
  post '/profile/:username/bikes/new', to: 'bikes#create'
  get '/profile/:username/bikes/:id', to: 'bikes#show', as: 'bike'
  get '/profile/:username/bikes/:id/edit', to: 'bikes#edit', as: 'edit_bike'
  patch '/profile/:username/bikes/:id/edit', to: 'bikes#update'
  delete '/profile/:username/bikes/:id', to: 'bikes#delete', as: 'delete_bike'

  get '/profile/:username/rides', to: 'rides#user_index', as: 'user_rides'
  get '/rides', to: 'rides#index'
  get '/rides/new', to: 'rides#new', as: 'new_ride'
  post '/rides', to: 'rides#create'
  get '/rides/:id', to: 'rides#show', as: 'ride'
  get '/rides/:id/edit', to: 'rides#edit', as: 'edit_ride'
  patch '/rides/:id/complete', to: 'rides#complete', as: 'complete_ride'
  patch '/rides/:id/join', to: 'rides#join', as: 'join_ride'
  patch '/rides/:id/leave', to: 'rides#leave', as: 'leave_ride'
  patch '/rides/:id', to: 'rides#update'
  delete '/rides/:id', to: 'rides#delete', as: 'delete_ride'
  get '/next-big-one', to: 'rides#next_big_one', as: 'next_big_one'
  get '/rides/:id/edit-stats', to: 'participants#edit', as: 'edit_ride_stats'
  patch '/rides/:id/edit-stats', to: 'participants#update'

  get '/leaderboard', to: 'leaderboard#index'

  get '/auth/github/callback' => 'sessions#omniauth'
end

app/models/bike.rb
class Bike < ActiveRecord::Base

    belongs_to :user
    has_many :components
    accepts_nested_attributes_for :components

    validates_presence_of :model
    validate :check_components

    def check_components
      if components[0].category == "" || components[0].model == "" || components[1].category == "" || components[1].model == "" 
        return errors.add :components, "Must Include 2 Componenets"
      end
    end

end

app/controllers/bikes_controller.rb
class BikesController < ApplicationController
    
    def index
        @user = User.find_by(username: params[:username])
    end

    def new
        if logged_in?
            if params[:username] == current_user.username
                @bike = Bike.new
                @bike.components.build(category: 'Groupset')
                @bike.components.build(category: 'Wheelset')
            else
                redirect_to user_bikes_path(current_user.username)
            end
        else
            redirect_to login_path
        end
    end

    def create
        @bike = Bike.new(bike_params)
        @bike[:user_id] = current_user.id
        if @bike.save
            redirect_to bike_path(@bike.user.username, @bike)
        else
            render :new
        end
    end

    def edit
        if logged_in?
            if params[:username] == current_user.username
                @bike = Bike.find(params[:id])
            else
                redirect_to user_bikes_path(current_user.username)
            end
        else
            redirect_to login_path
        end
    end

    def update
        @bike = Bike.find(params[:id])
        if @bike.update(bike_params)
            redirect_to bike_path(@bike.user.username, @bike)
        else
            render :edit
        end
    end

    def show
        @bike = Bike.find(params[:id])
    end

    def confirm_delete
        @bike = Bike.find(params[:id])
    end

    def delete
        @bike = Bike.find(params[:id])
        @bike.delete
        redirect_to user_bikes_path
    end

    private

    def bike_params
        params.require(:bike).permit(:model, components_attributes: [:id, :category, :model])
    end

end

app/views/bikes/edit.html.erb
<h2>Edit Bike</h2>

<%= form_for @bike, url: edit_bike_path do |f| %>

    <% if @bike.errors.any? %>
        <div style="color:red;">
            <h4>There were some errors:</h4>
            <ul>
                <% @bike.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <% if @bike.errors[:model].any? %> 
        <div class="field_with_errors">
    <% else %>
        <div>
    <% end %>
    <%= f.label name="Model:" %>
    <%= f.text_field :model, value: @bike.model %>
    </div>
    <br>

    <% if @bike.errors[:components].any? %> 
        <div class="field_with_errors">
    <% else %>
        <div>
    <% end %>
    <h3>Components:</h3>
    <%= f.fields_for :components do |c| %>
        <%= c.label name="Category:" %>
        <%= c.text_field :category %>
        <br>     
        <br>
        <%= c.label name="Model:" %>
        <%= c.text_field :model %><br>
        <br>
    <% end %>
    </div>
    <br>
    <%= f.submit %>
<% end %> 

app/views/bikes/index.html.erb
<%= link_to "Back to #{@user.username}'s Profile", user_path(@user.username) %>
<br>
<h2><%= @user.username %>'s Bikes</h2>
<% if @user == current_user %>
    <%= form_tag new_bike_path, method: :get do %>
        <%= submit_tag "Add Bike" %> 
    <% end %>
<% end %>
<br>
<% @user.bikes.each do |bike|%>
    <%= link_to "#{bike.model}", bike_path(bike.user.username, bike) %>
    <br>
    <br>
<% end %>

app/views/bikes/new.html.erb
<h2>Add Bike</h2>

<%= form_for @bike,  url: new_bike_path do |f| %>

    <% if @bike.errors.any? %>
        <div style="color:red;">
            <h4>There were some errors:</h4>
            <ul>
                <% @bike.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <% if @bike.errors[:model].any? %> 
        <div class="field_with_errors">
    <% else %>
        <div>
    <% end %>
    <%= f.label name="Model:" %>
    <%= f.text_field :model, value: @bike.model %>
    </div>
    <br>

    <% if @bike.errors[:components].any? %> 
        <div class="field_with_errors">
    <% else %>
        <div>
    <% end %>
    <h3>Components:</h3>
    <%= f.fields_for :components do |c| %>
        <%= c.label name="Category:" %>
        <%= c.text_field :category %>
        <br>     
        <br>
        <%= c.label name="Model:" %>
        <%= c.text_field :model %><br>
        <br>
    <% end %>
    </div>
    <br>
    <%= f.submit %>
<% end %> 

app/views/bikes/show.html.erb
<%= link_to "Back to #{@bike.user.username}'s Profile", user_path(@bike.user.username) %>
<h2><%= @bike.user.username %>'s <%= @bike.model%></h2>
<br>
Components:
<ul>
<% @bike.components.each do |comp| %>
    <li><%= comp.category %> - <%= comp.model %></li>
<% end %>
</ul>

<% if @bike.user == current_user %>
    <%= form_tag edit_bike_path, method: :get do %>
        <%= submit_tag "Edit Bike" %> 
    <% end %>
    <br>
    <%= form_tag delete_bike_path, method: :delete do %>
        <%= submit_tag "Delete Bike" %> 
    <% end %>
<% end %>