config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'static#home'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  get '/profile/:username', to: 'users#show', as: 'user'
  get '/profile/:username/bio', to: 'users#bio', as: 'user_bio'
  patch '/profile/:username/bio', to: 'users#edit_bio'

  get '/profile/:username/bikes', to: 'bikes#index', as: 'user_bikes'
  get '/profile/:username/bikes/new', to: 'bikes#new', as: 'new_bike'
  post '/profile/:username/bikes/new', to: 'bikes#create'
  get '/profile/:username/bikes/:id', to: 'bikes#show', as: 'bike'
  get '/profile/:username/bikes/:id/edit', to: 'bikes#edit', as: 'edit_bike'
  patch '/profile/:username/bikes/:id/edit', to: 'bikes#update'
  delete '/profile/:username/bikes/:id', to: 'bikes#delete', as: 'delete_bike'

  get '/profile/:username/rides', to: 'rides#user_index', as: 'user_rides'
  get '/rides', to: 'rides#index'
  get '/rides/new', to: 'rides#new', as: 'new_ride'
  post '/rides', to: 'rides#create'
  get '/rides/:id', to: 'rides#show', as: 'ride'
  get '/rides/:id/edit', to: 'rides#edit', as: 'edit_ride'
  patch '/rides/:id/complete', to: 'rides#complete', as: 'complete_ride'
  patch '/rides/:id/join', to: 'rides#join', as: 'join_ride'
  patch '/rides/:id/leave', to: 'rides#leave', as: 'leave_ride'
  patch '/rides/:id', to: 'rides#update'
  delete '/rides/:id', to: 'rides#delete', as: 'delete_ride'
  get '/next-big-one', to: 'rides#next_big_one', as: 'next_big_one'
  get '/rides/:id/edit-stats', to: 'participants#edit', as: 'edit_ride_stats'
  patch '/rides/:id/edit-stats', to: 'participants#update'

  get '/leaderboard', to: 'leaderboard#index'

  get '/auth/github/callback' => 'sessions#omniauth'
end

app/models/ride.rb
class Ride < ActiveRecord::Base

    belongs_to :user
    has_many :participants
    has_many :users, :through => :participants

    scope :leaderboard, -> { order('distance desc') }

    validates_presence_of :name, :date, :location, :category, :distance, :about
    validates :distance, numericality: { only_integer: true }
    
end

app/controllers/rides_controller.rb
class RidesController < ApplicationController

    def index
        @rides = Ride.all
    end

    def user_index
        @user = User.find_by(username: params[:username])
    end

    def new
        @ride = Ride.new
    end

    def create
        @ride = Ride.new(ride_params)
        if @ride.save
            @ride.users = []
            @ride.users << current_user
            redirect_to ride_path(@ride)
        else
            render :new
        end
    end

    def delete
        ride = Ride.find(params[:id])
        ride.delete
        redirect_to rides_path
    end

    def edit
        @ride = Ride.find(params[:id])
        if @ride.user != current_user
            redirect_to ride_path(@ride)
        end
    end
    
    def update
        @ride = Ride.find(params[:id])
        if @ride.update(ride_params)
            redirect_to ride_path(@ride)
        else
            render :new
        end
    end

    def complete
        @ride = Ride.find(params[:id])
        @ride.update(completed: true)
        redirect_to ride_path(@ride)
    end

    def join
        if logged_in?
            @ride = Ride.find(params[:id])
            @ride.users << current_user
            redirect_to ride_path(@ride)
        else
            redirect_to signup_path
        end
    end

    def leave
        @ride = Ride.find(params[:id])
        @ride.users.delete(current_user)
        redirect_to ride_path(@ride)
    end

    def show
        @ride = Ride.find(params[:id])
    end

    private

    def ride_params
        params.require(:ride).permit(:name, :date, :category, :distance, :about, :location, :user_id)
    end
    
end

app/views/rides/_form.html.erb
<% if @ride.errors.any? %>
    <div style="color:red;">
        <h4>There were some errors:</h4>
        <ul>
            <% @ride.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
        </ul>
    </div>
<% end %>

<%= form_for @ride do |f| %>

    <%= f.hidden_field :user_id, value: current_user.id %>

    <%= f.label name="Name:" %>
    <%= f.text_field :name %>
    <br>
    <br>
    <%= f.label name="Date (MM-DD-YYYY):" %>
    <%= f.text_field :date %>
    <br>
    <br>
    <%= f.label name="Location:" %>
    <%= f.text_field :location %>
    <br>
    <br>
    <%= f.label name="Category:" %>
    <%= f.select :category, ['CAT 1: 10-12 MPH', 'CAT 2: 12-15 MPH', 'CAT 3: 15-18 MPH', 'CAT 4: 18-22 MPH', 'CAT 5: 23+ MPH' ] %>
    <br>
    <br>
    <%= f.label name="Distance (Miles):" %>
    <%= f.text_field :distance %>
    <br>
    <br>
    <%= f.label name="About:" %>
    <%= f.text_area :about %>
    <br>
    <br>
    <%= f.submit %>
    
<% end %> 

app/views/rides/edit.html.erb
<h2>Editing Ride</h2>

<%= render 'form' %>

app/views/rides/index.html.erb
<h2>All Rides</h2>
<% if logged_in? %>
    <%= form_tag new_ride_path, method: :get do %>
        <%= submit_tag "New Ride" %> 
    <% end %>
<% end %>
<h4>Upcoming Rides</h4>
<ul>
<% @rides.each do |ride| %>
    <% if !ride.completed %>
        <li><%= link_to "#{ride.name}", ride_path(ride) %> - <%= ride.distance %> miles</li>
    <% end %>
<% end %>
</ul>
<h4>Past Rides</h4>
<ul>
<% @rides.each do |ride| %>
    <% if ride.completed %>
        <li><%= link_to "#{ride.name}", ride_path(ride) %> - <%= ride.distance %> miles</li>
    <% end %>
<% end %>
</ul>

app/views/rides/new.html.erb
<h2>New Ride</h2>

<%= render 'form' %>

app/views/rides/show.html.erb
<h2><%= @ride.name %></h2>
Created By: <%= link_to "#{@ride.user.username}", user_path(@ride.user.username) %>
<br>
<br>
<% if !@ride.completed %>
    <% if @ride.user == current_user %>
        <%= form_tag complete_ride_path, method: :patch do %>
            <%= submit_tag "Mark Completed" %> 
        <% end %>
        <br>
    <% end %>
    <% if !@ride.users.include?(current_user) %>
        <%= form_tag join_ride_path, method: :patch do %>
            <%= submit_tag "Join Ride" %> 
        <% end %>
    <% else %>
        <%= form_tag leave_ride_path, method: :patch do %>
            <%= submit_tag "Leave Ride" %> 
        <% end %>
    <% end %>
<% else %>
    <strong>This ride has been completed.</strong>
    <br>
    <br>
    <% if @ride.users.include?(current_user) %>
        <%= form_tag edit_ride_stats_path, method: :get do %>
            <% if !current_user.current_ride_stats(@ride).time%>
                <%= submit_tag "Add Ride Time" %>
            <% else %>
                <%= submit_tag "Edit Ride Time" %>
            <% end %>
        <% end %>
    <% end %>
<% end %>
<br>
<% if @ride.user == current_user %>
    <%= form_tag edit_ride_path, method: :get do %>
        <%= submit_tag "Edit Ride" %> 
    <% end %>
    <br>
    <%= form_tag delete_ride_path, method: :delete do %>
        <%= submit_tag "Delete Ride" %> 
    <% end %>
    <br>
<% end %>
<strong>Date:</strong> <%= @ride.date %>
<br>
<br>
<strong>Location:</strong> <%= @ride.location %>
<br>
<br>
<strong>Category:</strong> <%= @ride.category %>
<br>
<br>
<strong>Distance:</strong> <%= @ride.distance %> Miles
<br>
<br>
<strong>Details:</strong> <%= @ride.about %>
<br>
<br>
<table style="width: 500px; text-align: left">
    <tr>
        <th>Participant:</th>
        <th>Time:</th>
        <th>Avg. Speed:</th>
    </tr>
    <% Participant.ride(@ride.id).leaderboard.each do |participant| %>
        <tr>
        <% user = User.find(participant.user_id) %>
        <th style="font-weight: normal"><%= link_to "#{user.username}", user_path(user.username) %></th>
        <% if user.current_ride_stats(@ride).time %>
            <th style="font-weight: normal" ><%= user.current_ride_stats(@ride).time %></th>
            <th style="font-weight: normal" ><%= user.current_ride_stats(@ride).speed %> MPH</th>
        <% else %>
            <th style="font-weight: normal">--:--:--</th>
            <th style="font-weight: normal">--</th>
        <% end %>   
        </tr> 
    <% end %>
</table>

app/views/rides/user_index.html.erb
<%= link_to "Back to #{@user.username}'s Profile", user_path(@user.username) %>
<h2><%= @user.username %>'s Rides</h2>
<% if @user == current_user %>
    <%= form_tag new_ride_path, method: :get do %>
        <%= submit_tag "New Ride" %> 
    <% end %>
<% end %>

<h4>Upcoming Rides</h4>
<ul>
<% @user.rides.each do |ride| %>
    <% if !ride.completed %>
        <li><%= link_to "#{ride.name}", ride_path(ride) %> - <%= ride.distance %> miles</li>
    <% end %>
<% end %>
</ul>
<h4>Past Rides</h4>
<ul>
<% @user.rides.each do |ride| %>
    <% if ride.completed %>
        <li><%= link_to "#{ride.name}", ride_path(ride) %> - <%= ride.distance %> miles</li>
    <% end %>
<% end %>
</ul>