config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'static#home'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  get '/profile/:username', to: 'users#show', as: 'user'
  get '/profile/:username/bio', to: 'users#bio', as: 'user_bio'
  patch '/profile/:username/bio', to: 'users#edit_bio'

  get '/profile/:username/bikes', to: 'bikes#index', as: 'user_bikes'
  get '/profile/:username/bikes/new', to: 'bikes#new', as: 'new_bike'
  post '/profile/:username/bikes/new', to: 'bikes#create'
  get '/profile/:username/bikes/:id', to: 'bikes#show', as: 'bike'
  get '/profile/:username/bikes/:id/edit', to: 'bikes#edit', as: 'edit_bike'
  patch '/profile/:username/bikes/:id/edit', to: 'bikes#update'
  delete '/profile/:username/bikes/:id', to: 'bikes#delete', as: 'delete_bike'

  get '/profile/:username/rides', to: 'rides#user_index', as: 'user_rides'
  get '/rides', to: 'rides#index'
  get '/rides/new', to: 'rides#new', as: 'new_ride'
  post '/rides', to: 'rides#create'
  get '/rides/:id', to: 'rides#show', as: 'ride'
  get '/rides/:id/edit', to: 'rides#edit', as: 'edit_ride'
  patch '/rides/:id/complete', to: 'rides#complete', as: 'complete_ride'
  patch '/rides/:id/join', to: 'rides#join', as: 'join_ride'
  patch '/rides/:id/leave', to: 'rides#leave', as: 'leave_ride'
  patch '/rides/:id', to: 'rides#update'
  delete '/rides/:id', to: 'rides#delete', as: 'delete_ride'
  get '/next-big-one', to: 'rides#next_big_one', as: 'next_big_one'
  get '/rides/:id/edit-stats', to: 'participants#edit', as: 'edit_ride_stats'
  patch '/rides/:id/edit-stats', to: 'participants#update'

  get '/leaderboard', to: 'leaderboard#index'

  get '/auth/github/callback' => 'sessions#omniauth'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <style>
    body {
        margin: 0;
        font-family: Arial, Helvetica, sans-serif;
    }

    .page {
        padding: 25px;  
    }

    .topnav {
        overflow: hidden;
        background-color: #333;
    }

    .topnav a {
        float: left;
        color: #f2f2f2;
        text-align: center;
        padding: 14px 16px;
        text-decoration: none;
        font-size: 17px;
    }

    .topnav a:hover {
        background-color: #ddd;
        color: black;
    }

    .topnav a.active {
        background-color: #04AA6D;
        color: white;
    }

    .field_with_errors {
        padding: 2px;
        background-color: red;
        display: table;
    }

    .row {
        display: flex;
    }

    .column {
        flex: 50%;
    }
    
    </style>
    <title>VeloBuds</title>
    <% if logged_in? %>
      <div class="topnav">
        <%= link_to "VeloBuds", root_path %>
        <%= link_to "Profile", user_path(current_user.username) %>
        <%= link_to "Rides", rides_path %>
        <%= link_to "Leaderboard", leaderboard_path %>
        <%= link_to "Log Out", logout_path, method: :delete %>
        
      </div>
    <% else %>
      <div class="topnav">
        <%= link_to "VeloBuds", root_path %>
        <%= link_to "Log In", login_path %>
        <%= link_to "Sign Up", signup_path %>
      </div>
    <% end %>
  </head>
  
  <body>
    <div class="page">
    <%= yield %>
    </div>
  </body>
</html>